export interface ChapterCommentInput {
  org: string;
  repo: string;
  number: number;
  webBaseUrl: string;
  commitSha: string;
  chapters: { order: number; title: string }[];
}

function chapterUrl(input: ChapterCommentInput, order: number): string {
  const base = input.webBaseUrl.replace(/\/+$/, "");
  return `${base}/${input.org}/${input.repo}/pull/${input.number}/chapters/${order}`;
}

/** Build the Folio bot comment: an intro line + a numbered chapter table. */
export function buildChapterCommentBody(input: ChapterCommentInput): string {
  const count = input.chapters.length;
  const noun = count === 1 ? "chapter" : "chapters";
  const rows = input.chapters
    .map((c) => `| ${c.order} | [${c.title}](${chapterUrl(input, c.order)}) |`)
    .join("\n");

  return [
    `Ready to review this PR? Folio has broken it down into ${count} individual ${noun} for you:`,
    "",
    "| | Title |",
    "| --- | --- |",
    rows,
    "",
    `Chapters generated by Folio for commit \`${input.commitSha}\`.`,
  ].join("\n");
}
